pde_name: "2D_Darcy_Flow"
model_name: "FNO"
if_training: True
continue_training: False
model_path: "./checkpoint/2D_DarcyFlow_beta1.0_Train/2D_DarcyFlow_beta1.0_Train_FNO-best.pt"
output_dir: "./checkpoint/"
save_period: 20
# training args
seed: 0
training_type: "single"
t_train: 2
initial_step: 1
unroll_step: 1
epochs: 500
# dataset args 
dataset:
  file_name: "2D_DarcyFlow_beta1.0_Train.hdf5"
  saved_folder: ./dataset/
  reduced_resolution: 2
  reduced_resolution_t: 1
  reduced_batch: 10
# dataloader args
dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: False
# model args
model:
  num_channels: 1
  modes: 12
  width: 20
  output: 1
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5