pde_name: "2D_Compressible_NS"
model_name: "FNO"
if_training: True
continue_training: False
model_path: "./checkpoint/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train_FNO-best.pt"
output_dir: "./checkpoint/"
save_period: 20
# training args
seed: 0
training_type: "autoregressive"
t_train: 21
initial_step: 10
unroll_step: 20
epochs: 500
# dataset args 
dataset:
  single_file: True
  file_name: "2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5"
  saved_folder: ./dataset/
  reduced_resolution: 2
  reduced_resolution_t: 1
  reduced_batch: 10
# dataloader args
dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: True
# model args
model:
  num_channels: 4
  modes: 12
  width: 128
  output: 84
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5